### ISSUE TITLE
Migrations to make full use of types

### ISSUE THREAD

**Issue by cornernote** [Insolita/yii2-migrik#10]
Im sending from my mobile, so if it doesn't fully make sense I'll clarify when I have a keyboard in front of me... 

Basically if you want to set a field as null or not null there is a better way.  Have a look at how it's done in this migration:

https://github.com/dmstr/yii2-pages-module/blob/master/migrations/m150309_153255_create_tree_manager_table.php

**Comment by Insolita** [comment]
So you want migrations in new yii2-style with functions, instead of sql string? 
In first, i planning to refactor column generation method, and to make it flexible for external customizing, after that i will think about new-style variant, I wrote this plugin when this feature not has been realeased in framework

**Comment by Insolita** [comment]
There are two opposite variants - make application with maximum independent from storage; and with maximum usage of all features of current database, and in different cases both variants may be good, but require different approach

**Comment by cornernote** [comment]
That's true, but if you want to utilise a particular database then you
could simply use the approach you initially suggested where your migration
runs the sql. It would seem your module is more useful in the generic
database option.

**Comment by Insolita** [comment]
include in next release
